export enum Subjects {
  CommerceCreated = 'commerce:created',
  CommerceUpdated = 'commerce:updated',
  CommerceBannerAdded = 'commerce:bannerAdded',
  CommerceBannerChosen = 'commerce:bannerChosen',
  CommerceBannerUpdated = 'commerce:bannerUpdated',
  CommerceMainDesignUpdated = 'commerce:mainDesignUpdated',
  CommerceWarehouseAdded = 'commerce:warehouseAdded',
  CommerceWarehouseRemoved = 'commerce:warehouseRemoved',
  CommerceDateExceptionCreated = 'commerce:exceptionDateCreated',
  CommerceDayExceptionCreated = 'commerce:exceptionDayCreated',
  CommerceExceptionRemoved = 'commerce:exceptionRemoved',
  CommerceExceptionUpdated = 'commerce:exceptionUpdated',

  WarehouseCreated = 'warehouse:created',
  WarehouseShipMethodConnected = 'warehouse:shipMethodConnected',
  WarehouseShipMethodDisconnected = 'warehouse:shipMethodDisconnected',

  ShipMethodCreated = 'shipMethod:created',
  ShipMethodDocUpserted = 'shipMethod:docUpserted',
  ShipMethodUpdated = 'shipMethod:updated',
  ShipMethodRemoved = 'shipMethod:removed',
  ShipMethodDateExceptionCreated = 'shipMethod:exceptionDateCreated',
  ShipMethodDayExceptionCreated = 'shipMethod:exceptionDayCreated',
  ShipMethodExceptionRemoved = 'shipMethod:exceptionRemoved',
  ShipMethodExceptionUpdated = 'shipMethod:exceptionUpdated',

  ItemCreated = 'item:created',
  ItemDocUpserted = 'item:docUpserted',
  ItemExitDateUpdated = 'item:exitDateUpdated',
  ItemLimitsUpdated = 'item:limitsUpdated',
  ItemPriceUpdated = 'item:priceUpdated',
  ItemSellStarted = 'item:sellStarted',
  ItemUpdated = 'item:updated',
  ItemWarehouseAdded = 'item:warehouseAdded',
  ItemWarehouseRemoved = 'item:warehouseRemoved',
  ItemIsHidden = 'item:hidden',
  ItemIsRevealed = 'item:revealed',

  StockAutoSet = 'stock:autoSet',
  StockCreated = 'stock:created',
  StockDisposed = 'stock:disposed',
  StockDisposeUpdated = 'stock:disposeUpdated',
  StockMovedToHistory = 'stock:movedToHistory',
  StockWarehouseTransfered = 'stock:warehouseTransfered',
  StockReserved = 'stock:stockReserved',
  StockUpdated = 'stock:updated',
  StockReleasedDueExit = 'stock:releasedDueExit',
  StockOrderRecorded = 'stock:orderRecorded',
  StockPlanDetailRecorded = 'stock:planDetailRecorded',
  StockConsumed = 'stock:consumed',
  StockOrderCancel = 'stock:orderCancelled',
  StockReleasedPlanExceptionAdd = 'stock:releasedPlanExceptionAdd',
  StockReleasedPlanArchive = 'stock:releasedPlanArchive',
  StockReleasedOrderNoStock = 'stock:releasedOrderNoStock',
  StockReleasedPlanDetailArchive = 'stock:releasedPlanDetailArchive',
  StockItemDuplicated = 'stock:itemDuplicated',

  StockRequested = 'stock:requested',
  StockRequestedProduct = 'stock:requestedProduct',
  StockRequestedProductGroups = 'stock:requestedProductGroups',
  StockRequestedPlanDetailsExceptionRemoved = 'stock:requestedPlanDetailsExceptionRemoved',
  StockRequestUpdated = 'stock:requestUpdated',
  StockReleased = 'stock:released',

  StockReserveLogged = 'stock:reserveLogged',
  StockOrderNoStockLogged = 'stock:orderNoStockLogged',
  StockPlanArchiveLogged = 'stock:planArchiveLogged',
  StockPlanDetailArchiveLogged = 'stock:planDetailArchiveLogged',
  StockPlanOrderCreatedLogged = 'stock:planOrderCreatedLogged',
  StockPlanExceptionAddLogged = 'stock:planExceptionAddLogged',
  StockDisposeLogged = 'stock:disposeLogged',
  StockDisposeUpdateLogged = 'stock:disposeUpdateLogged',
  StockOrderCancelLogged = 'stock:orderCancelLogged',

  ProductCommerceAdded = 'product:CommerceAdded',
  ProductCommerceUpdated = 'product:CommerceUpdated',
  ProductCommerceRemoved = 'product:CommerceRemoved',
  ProductCreated = 'product:created',
  ProductDocUpserted = 'product:docUpserted',
  ProductEventAdded = 'product:eventAdded',
  ProductSearchDataAdded = 'product:searchDataAdded',
  ProductSearchDataRemoved = 'product:searchDataRemoved',
  ProductUpdated = 'product:updated',
  ProductLastOrderTimeUpdated = 'product:lastOrderTimeUpdated',
  ProductExitDateUpdated = 'product:exitDateUpdated',
  ProductRawPriceUpdated = 'product:rawPriceUpdatd',
  ProductItemsUpated = 'product:itemsUpdated',
  ProductCategoryAdded = 'product:categoryAdded',
  ProductCategoryRemoved = 'product:categoryRemoved',
  ProductHidden = 'product:hidden',
  ProductIsRevealed = 'product:revealed',

  ProductOptionArchived = 'productOption:archived',
  ProductOptionCreated = 'productOption:created',
  ProductOptionDocUpserted = 'productOption:docUpserted',
  ProductOptionUpdated = 'productOption:updated',

  PlanArchived = 'plan:archived',
  PlanCleared = 'plan:cleared',
  PlanCreated = 'plan:created',
  PlanDefaultSet = 'plan:defaultSet',
  PlanReceiverUpdated = 'plan:receiverUpdated',
  PlanDetailAdded = 'plan:detailAdded',
  PlanDetailUpdated = 'plan:detailUpdated',
  PlanDetailExceptionAdded = 'plan:detailexceptionAdded',
  planDetailExitDateAdded = 'plan:exitDateAdded',
  PlanOrderCreated = 'plan:orderCreated',
  PlanDetailArchived = 'plan:detailArchived',
  PlanDetailExceptionUpdated = 'plan:detailExceptionUpdated',
  PlanDetailExceptionRemoved = 'plan:detailExceptionRemoved',
  PlanDetailWaitingFinished = 'plan:detailWaitingFinished',
  PlanDetailsAdded = 'plan:detailsAdded',

  OrderCancelled = 'order:cancelled',
  OrderCreated = 'order:created',
  OrderIsNoStock = 'order:isNoStock',
  OrderUpdatedReceiver = 'order:updatedReceiver',
  OrderPaidCreated = 'order:paidCreated',
  OrderWantDateChanged = 'order:shippingDateChanged',
  OrderPaymentConfirmed = 'order:paymentConfirmed',
  OrderPaymentFailed = 'order:paymentFailed',
  OrderPickedUp = 'order:pickedUp',
  OrderPrepared = 'order:prepared',
  OrderShipping = 'order:shipping',
  OrderShipped = 'order:shipped',
  OrderFeedbackRecorded = 'order:feedbackRecorded',
  OrdersPreFromOutsideCreated = 'order:fromOutsidePreCreated',
  OrderFromOutsideCreated = 'order:fromOutsideCreated',
  OrderFromOutsideCancelled = 'order:fromOutsideCancelled',
  OrderDirectPickUp = 'order:directPickUp',

  ShipCreated = 'ship:created',
  ShipsShipping = 'ship:shipping',
  ShipsShipped = 'ship:shipped',
  ShipsCancelled = 'ship:cancelled',
  ShipsUpdated = 'ship:updated',
  ShipProductsUpdated = 'ship:productsUpdated',
  ShipReceiverUpdated = 'ship:receiverUpdated',
  ShipBoxTypeUpdated = 'ship:boxTypeUpdated',
  ShipsUploaded = 'ship:uploaded',
  ShipsDownloaded = 'ship:downloaded',
  ShipAdded = 'ship:added',
  ShipRemoved = 'ship:removed',

  PaymentCreated = 'payment:created',
  PaymentBillingCardAdded = 'payment:billingCardAdded',
  PaymentBillingCardRemoved = 'payment:billingCardRemoved',
  PaymentCancelled = 'payment:cancelled',
  PaymentMileageRewarded = 'payment:mileageRewarded',
  PaymentReviewRewarded = 'payment:reviewRewarded',
  PaymentMileagePlanCreated = 'payment:mileagePlanCreated',
  PaymentMileagePlanRemoved = 'payment:mileagePlanRemoved',
  PaymentUpdated = 'payment:updated',

  MileageRewarded = 'mileage:rewarded',
  MileageSpendCreated = 'mileage:spendCreated',
  MileageSpendUpdated = 'mileage:spendUpdated',

  FeedbackCreated = 'feedback:created',
  FeedbackCategorySelected = 'feedback:categorySelected',
  FeedbackUpdated = 'feedback:updated',
  FeedbackCancelRequestAccepted = 'feedback:cancelRequestAccepted',
  FeedbackAdminRewarded = 'feedback:adminRewarded',
  FeedbackChecked = 'feedback:checked',
  FeedbackReplied = 'feedback:replied',
  FeedbackReplyEdited = 'feedback:replyEdited',
  FeedbackReplyChecked = 'feedback:replyChecked',
  FeedbackIsCompleted = 'feedback:isCompleted',
  FeedbackArchived = 'feedback:archived',

  ReportCreated = 'report:created',
  ReportAccepted = 'report:accepted',
  ReportRejected = 'report:rejected',

  UserAppTokenLogin = 'user:appTokenLogin',
  UserKakaoLogin = 'user:kakaoLogin',
  UserKakaoRegistered = 'user:kakaoRegister',
  UserAppleLogin = 'user:appleLogin',
  UserAppleRegistered = 'user:appleRegister',
  UserRegistered = 'user:registered',
  UserLogin = 'user:login',
  UserArchived = 'user:archived',
  UserUpdated = 'user:updated',
  UserUpsertReceiver = 'user:upsertReceiver',

  AdmissionTicketCreated = 'admissionTicket:created',
  AdmissionTicketUpdated = 'admissionTicket:updated',

  NotificationCreated = 'notification:created',
  NotificationSentMessageApistoreKakao = 'notification:sentMessageApistoreKakao',
  NotificationSentMessageFcm = 'notification:sentMessageFcm',
  NotificationSentMessageSolapi = 'notification:sentMessageSolapi',

  DynamicLinkCreated = 'dynamicLink:created'
}
